.PHONY: all
all: prestudy.pdf

FILES=		prestudy.tex prestudy.bib

prestudy.pdf: ${FILES}


.PHONY: clean
clean:
	${RM} prestudy.pdf


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
